name: ackaf
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:  ^1.0.3
  modal_bottom_sheet: ^3.0.0
  flutter_rating_bar: ^4.0.0
  intl_phone_field: ^3.2.0
  dotted_border: ^2.1.0
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  http_parser: ^4.0.2
  dropdown_button2: ^2.3.9
  path: ^1.9.0
  file_picker: ^8.1.2
  url_launcher: ^6.3.0
  riverpod_annotation: ^2.3.5
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  intl: ^0.18.1
  youtube_player_flutter: ^8.1.2
  smooth_page_indicator: ^1.2.0+3
  pinput: ^5.0.0
  web_socket_client: ^0.1.0
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.3.2

  socket_io_client: ^3.0.0-beta.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_dotenv: ^5.1.0
  minio_flutter: ^0.0.1
  flutter_upgrade_version: ^1.1.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:

    - assets/
    - assets/icons/
    - .env

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/akcaf_icon.png"

   
